// @ts-nocheck
  // This file is autogenerated by scripts/build-registry.ts
  // Do not edit this file directly.
  import * as React from "react"
  
  export const Index: Record<string, any> = {
    "default": {
      "accordion": {
        name: "accordion",
        type: "registry:component",
        slug: "/components/accordion",
        thumbnail: "undefined",
        number: "undefined",
        registryDependencies: undefined,
        files: ["components/ui/accordion.tsx"],
        component: React.lazy(() => import("@/components/ui/accordion.tsx")),
        source: "",
        category: "undefined",
        subcategory: "undefined",
        chunks: []
      },
    },
  }
  